### ISSUE TITLE
Is this gem still being maintained?

### ISSUE THREAD

**Issue by nimashariatian** [clbustos/rinruby#19]
His guys, this looks very interesting, I was wondering if this gem still being maintained?

**Comment by sebastianzillessen** [comment]
Hmm, doesn't look like it is (e.g the linked page is not accessible, 2 years of no updates, 10 issues open, ...), but it looks really interesting!

Maybe we should continue to work on it?

**Comment by thoughtafter** [comment]
Save yourself time and hassle and use rserve and rserve-client instead:
https://github.com/clbustos/Rserve-Ruby-client

**Comment by nimashariatian** [comment]
thank you @thoughtafter !
