### ISSUE TITLE
Matrix comparison on spec fails on Ruby 2.1.1

### ISSUE THREAD

**Issue by clbustos** [clbustos/rinruby#34]
Spec "RinRuby R interface on pull should pull a Matrix" fails on Ruby 2.1.1, but not on any other Ruby version. The problems lies on the comparison method. Maybe we should use "be_within" to allow some degree of error (e-10 or less) between ruby and R.

**Comment by fenrir-naru** [comment]
This may occur not only Ruby 2.1.1, but also other versions, for example, [2.5 on my Travis-CI](https://travis-ci.org/fenrir-naru/rinruby/jobs/417884020#L1114).
I introduce more mitigation with 95c2280 included in PR #35 .

**Comment by clbustos** [comment]
Ok, I will close it. Thanks for the new features!
